{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "3.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.46"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.3.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.5.6.jar",
          "url": "spring-boot-starter-validation-3.5.6.jar",
          "size": 4767,
          "sha512": "904fdf62ea0879598f88be2accd607cc54f7d030462bb755123d1bbb11ac4097c14458619f0997fd04c20ca4ca9b1429a095a48cc74e25d15e4539650fcde9cf",
          "sha256": "0d17ce1b42d2a2a3cf69fd68c8554249693a7cbb6d6e963ba9a13adaea67103e",
          "sha1": "2ec647ae8e16b09a4aee4a17c0e7736f6214aacc",
          "md5": "9bb80efe58d742096e242be61b2b5afa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.46"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.3.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.5.6.jar",
          "url": "spring-boot-starter-validation-3.5.6.jar",
          "size": 4767,
          "sha512": "904fdf62ea0879598f88be2accd607cc54f7d030462bb755123d1bbb11ac4097c14458619f0997fd04c20ca4ca9b1429a095a48cc74e25d15e4539650fcde9cf",
          "sha256": "0d17ce1b42d2a2a3cf69fd68c8554249693a7cbb6d6e963ba9a13adaea67103e",
          "sha1": "2ec647ae8e16b09a4aee4a17c0e7736f6214aacc",
          "md5": "9bb80efe58d742096e242be61b2b5afa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.5.6-javadoc.jar",
          "url": "spring-boot-starter-validation-3.5.6-javadoc.jar",
          "size": 4767,
          "sha512": "3643dcb4ec3e0c80d8dfed1f5f32b5f2ac1dfa573a5a73d06a4e368622e5e9546d1557c64c4c0b50f54a9bce36e4e68e382c29672572d8174737529830a67bdd",
          "sha256": "7e12d9c4a58d8064ebb832270604e2650117616e722744bde9526b4421cdb5e4",
          "sha1": "e33f373c108c2dc902fafedcb6b2e3cd62fcb9a3",
          "md5": "3d9a96ec198737825317601b32c8a952"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.5.6-sources.jar",
          "url": "spring-boot-starter-validation-3.5.6-sources.jar",
          "size": 4767,
          "sha512": "3643dcb4ec3e0c80d8dfed1f5f32b5f2ac1dfa573a5a73d06a4e368622e5e9546d1557c64c4c0b50f54a9bce36e4e68e382c29672572d8174737529830a67bdd",
          "sha256": "7e12d9c4a58d8064ebb832270604e2650117616e722744bde9526b4421cdb5e4",
          "sha1": "e33f373c108c2dc902fafedcb6b2e3cd62fcb9a3",
          "md5": "3d9a96ec198737825317601b32c8a952"
        }
      ]
    }
  ]
}
