{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "6.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.5.5.jar",
          "url": "spring-security-web-6.5.5.jar",
          "size": 1052263,
          "sha512": "80b97ffd2ac55bb609404acadca9951e130f090dece3e1d984b9decf56eefbba628687da7775cc67734961d14a3e8c320782985d5cc639c9419de3be426f2a10",
          "sha256": "bab7cf0921faba78b92c48ffd3f74c88de1bebb658e4ace70dcb50f15a287d8c",
          "sha1": "53362443076c948cf1fbdd078802ef58917b5938",
          "md5": "8f1683b9ea26880594eabc1563af1d1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.5.5.jar",
          "url": "spring-security-web-6.5.5.jar",
          "size": 1052263,
          "sha512": "80b97ffd2ac55bb609404acadca9951e130f090dece3e1d984b9decf56eefbba628687da7775cc67734961d14a3e8c320782985d5cc639c9419de3be426f2a10",
          "sha256": "bab7cf0921faba78b92c48ffd3f74c88de1bebb658e4ace70dcb50f15a287d8c",
          "sha1": "53362443076c948cf1fbdd078802ef58917b5938",
          "md5": "8f1683b9ea26880594eabc1563af1d1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.5.5-javadoc.jar",
          "url": "spring-security-web-6.5.5-javadoc.jar",
          "size": 2300929,
          "sha512": "5e60f93a98d0752249a696e8dd46156d21476de29948532b13df518da1770557b0a8c453bed0860dc3930c72454922777d8abf38e9a8d733abe157b2c7c79f3f",
          "sha256": "3e2fc822e78315f6848600f8936f5f10bfb78dd0f0a564b3f7245599e1381d10",
          "sha1": "925359c4d47c7846d42c1a56d7d63c9abe834e0f",
          "md5": "9493d8944a4f1065fb176cf2620c4c10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.5.5-sources.jar",
          "url": "spring-security-web-6.5.5-sources.jar",
          "size": 867848,
          "sha512": "f62aa2c92d35bd8bb996282d75e69049595da7bcb7ddc3d50c7941ab70bdcc6f4ea65984f9ed111ad988ae0eb20ca2dae70e318c60ede025b515fed205c38795",
          "sha256": "8f259c70d34b9f934105841b6f5017ea4ab6180295e1db6efadafa34c40f80c1",
          "sha1": "36dd9c524339bd557e5e6bb0bf1e91af46e4e8ce",
          "md5": "b2f8079248a9008def93bcc0eafd6e5e"
        }
      ]
    }
  ]
}
