{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "3.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.5.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.5.6.jar",
          "url": "spring-boot-starter-security-3.5.6.jar",
          "size": 4742,
          "sha512": "358e1472f840a717741dee9e999f3f2d3a01769f76591b8427aae25acc678affb0f4e769f1f44b01d9dcdfd595d5b0f8209d536ce982b8a16a169dd21303ec31",
          "sha256": "105eefcdfe4583031391ddc28166e5d090e56fcf6125db58537e440a8df89a83",
          "sha1": "000f784752820b4e59f1e144e6d208d04fa27da9",
          "md5": "2d259382210e2c5fa4cdb83667501cce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.5.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.5.6.jar",
          "url": "spring-boot-starter-security-3.5.6.jar",
          "size": 4742,
          "sha512": "358e1472f840a717741dee9e999f3f2d3a01769f76591b8427aae25acc678affb0f4e769f1f44b01d9dcdfd595d5b0f8209d536ce982b8a16a169dd21303ec31",
          "sha256": "105eefcdfe4583031391ddc28166e5d090e56fcf6125db58537e440a8df89a83",
          "sha1": "000f784752820b4e59f1e144e6d208d04fa27da9",
          "md5": "2d259382210e2c5fa4cdb83667501cce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.5.6-javadoc.jar",
          "url": "spring-boot-starter-security-3.5.6-javadoc.jar",
          "size": 4742,
          "sha512": "358e1472f840a717741dee9e999f3f2d3a01769f76591b8427aae25acc678affb0f4e769f1f44b01d9dcdfd595d5b0f8209d536ce982b8a16a169dd21303ec31",
          "sha256": "105eefcdfe4583031391ddc28166e5d090e56fcf6125db58537e440a8df89a83",
          "sha1": "000f784752820b4e59f1e144e6d208d04fa27da9",
          "md5": "2d259382210e2c5fa4cdb83667501cce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.5.6-sources.jar",
          "url": "spring-boot-starter-security-3.5.6-sources.jar",
          "size": 4742,
          "sha512": "358e1472f840a717741dee9e999f3f2d3a01769f76591b8427aae25acc678affb0f4e769f1f44b01d9dcdfd595d5b0f8209d536ce982b8a16a169dd21303ec31",
          "sha256": "105eefcdfe4583031391ddc28166e5d090e56fcf6125db58537e440a8df89a83",
          "sha1": "000f784752820b4e59f1e144e6d208d04fa27da9",
          "md5": "2d259382210e2c5fa4cdb83667501cce"
        }
      ]
    }
  ]
}
