{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "6.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.5.5.jar",
          "url": "spring-security-config-6.5.5.jar",
          "size": 2108050,
          "sha512": "678f0314bc76c44930ade7194834d9e2e8ea3e68e65237c8def9b8623aa20b0cb7c8e3b728a17e31d7fbb90280c0561afe43a69ae4b66233a4314fe93dc8440f",
          "sha256": "d884887c4d1106624e9724db199d8abdf4c3b94678359d5d6eac12f69b0daea2",
          "sha1": "e647f8334d2d4578f7b553e705a409017ac37be1",
          "md5": "938dbac0af2a497953e8b0e20b5d3e60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.5.5.jar",
          "url": "spring-security-config-6.5.5.jar",
          "size": 2108050,
          "sha512": "678f0314bc76c44930ade7194834d9e2e8ea3e68e65237c8def9b8623aa20b0cb7c8e3b728a17e31d7fbb90280c0561afe43a69ae4b66233a4314fe93dc8440f",
          "sha256": "d884887c4d1106624e9724db199d8abdf4c3b94678359d5d6eac12f69b0daea2",
          "sha1": "e647f8334d2d4578f7b553e705a409017ac37be1",
          "md5": "938dbac0af2a497953e8b0e20b5d3e60"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.5.5-javadoc.jar",
          "url": "spring-security-config-6.5.5-javadoc.jar",
          "size": 1209568,
          "sha512": "54d861b0ff8d4213613b044a85653ec716df489e97fb862d25a572b4cee99866ed067701a4e57634cc496813f9ccbb5c4e7ecd7e855257522ce95ce4ea2fc75e",
          "sha256": "e926dfdc416aa496d735f910fba2f9266288bfb09cfde4f48f01dbbae427a5c9",
          "sha1": "6762deb9d9474fefd3dbc7e1eae19e5b0e3885a8",
          "md5": "d8eabdc3ef0f713f58608e00b777e151"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.5.5-sources.jar",
          "url": "spring-security-config-6.5.5-sources.jar",
          "size": 1449280,
          "sha512": "e62a05c5519760b31c87b280818d10767a006d8eeebb4314e56af3ac6c0170fc04b5b72966c4c6eb70d63d1ca703ab1d5e7b83f24611dfbeb54439d38283b8e1",
          "sha256": "b66101776fe3f81f53c4f3dc13c3af4321670cf50fd1949923a5f1ba89522989",
          "sha1": "731847b0daccab042ee65426421fdf413d67f743",
          "md5": "ecdeae04aba34e25de7f3feb58c5fa1e"
        },
        {
          "name": "spring-security-config-6.5.5-sources.jar",
          "url": "spring-security-config-6.5.5-sources.jar",
          "size": 1449280,
          "sha512": "e62a05c5519760b31c87b280818d10767a006d8eeebb4314e56af3ac6c0170fc04b5b72966c4c6eb70d63d1ca703ab1d5e7b83f24611dfbeb54439d38283b8e1",
          "sha256": "b66101776fe3f81f53c4f3dc13c3af4321670cf50fd1949923a5f1ba89522989",
          "sha1": "731847b0daccab042ee65426421fdf413d67f743",
          "md5": "ecdeae04aba34e25de7f3feb58c5fa1e"
        }
      ]
    }
  ]
}
