{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator",
    "version": "3.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-3.5.6.jar",
          "url": "spring-boot-actuator-3.5.6.jar",
          "size": 703716,
          "sha512": "80c0013f4f2f55c6ceda7a7a9ae639291ad5f03509c48b0c1f50dd2d19841e632ff8a50b3e63838ce4b1fa8842122852e90fafbcc186a450ddce27eb1bb28c85",
          "sha256": "b06143d365a337df5173119fe8d69424a7467b5ad4226034b7e6ed3a2b11c158",
          "sha1": "cf67879f31058782b4a04a4c19978f30c5cb477c",
          "md5": "f1f83f307ca7677fdc17bcd75896d5a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-3.5.6.jar",
          "url": "spring-boot-actuator-3.5.6.jar",
          "size": 703716,
          "sha512": "80c0013f4f2f55c6ceda7a7a9ae639291ad5f03509c48b0c1f50dd2d19841e632ff8a50b3e63838ce4b1fa8842122852e90fafbcc186a450ddce27eb1bb28c85",
          "sha256": "b06143d365a337df5173119fe8d69424a7467b5ad4226034b7e6ed3a2b11c158",
          "sha1": "cf67879f31058782b4a04a4c19978f30c5cb477c",
          "md5": "f1f83f307ca7677fdc17bcd75896d5a2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-3.5.6-javadoc.jar",
          "url": "spring-boot-actuator-3.5.6-javadoc.jar",
          "size": 1506717,
          "sha512": "e5b9c51392a61cece276bcdf6de572ce3493177d7e6d04ae1a14fe3ae3f9a87774ad01a03096dc127c0cdc99d58d8a3170150bebd5c0ca22f68486a07f43c447",
          "sha256": "a608697d2438230a62f0cfc0fe19da37c3a6bf027d879d96ea3a2c219dbdec21",
          "sha1": "57109d224c26bf1274c51ad1d41e9ad47e76df27",
          "md5": "e69597df7b1e225359fe8ec03a1d2825"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-3.5.6-sources.jar",
          "url": "spring-boot-actuator-3.5.6-sources.jar",
          "size": 470549,
          "sha512": "b303acd4b500f6cf76eba74f0771cc713b1495db236786b71953142cb028d04502ea5486011cfb9983281be57302e31ac5140f9ae0992fa58c742d95ccf3ef77",
          "sha256": "4f0ce1594396a6c0126c36bf62687058a882dab8e1ababe3d72b99928711979a",
          "sha1": "66fdcaed6dd3afe9303a5cc5e9df99f5c6c8f62e",
          "md5": "9d8c61ce4976f5d83145c125a5a173a7"
        }
      ]
    }
  ]
}
